spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${CORPORATIONX_DB_URL:jdbc:postgresql://localhost:15432/corporationx}
    username: ${CORPORATIONX_DB_USER:user}
    password: ${CORPORATIONX_DB_PASSWORD:password}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: ${CORPORATIONX_REDIS_PORT:16379}
      host: localhost
      channel:
        profile-view: profile_view_channel

server:
  port: 8086

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082
